.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "March 31, 2014"
.SH NAME
sl \- display animations aimed to correct users who accidentally enter sl instead of ls.
.SH SYNOPSIS
.B sl
[
.B \-acdeFlw
]
.SH DESCRIPTION
.B sl
Displays animations aimed to correct users who accidentally enter sl instead of ls.  SL stands for Steam Locomotive.
.PP
.TP
.B \-a
An accident is occurring. People cry for help.
.TP
.B \-c
C51 appears instead of D51.
.TP
.B \-d
Disco mode. Alternate colors during animation.
.TP
.B \-e
Escape. Allow interrupt by Ctrl+C.
.TP
.B \-F
It flies like the galaxy express 999.
.TP
.B \-l
Little version.
.TP
.B \-w
Windy day. Locomotive moves faster.
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
Toyoda Masashi (mtoyoda@acm.org)
