.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "April 18, 2020"
.SH NAME
sl \- cure your bad habit of mistyping
.SH SYNOPSIS
.B sl
[
.B \-alFc
]
.SH DESCRIPTION
.B sl
is a highly advanced animation program for curing your bad habit of mistyping.
.PP
.TP
.B \-a
An accident is occurring. People cry for help.
.TP
.B \-l
Little version.
.TP
.B \-F
It flies like the galaxy express 999. Overrides previous -t.
.TP
.B \-c
C51 appears instead of D51.
.TP
.B \-t
It has tracks. Much realism. Overrides previous -F.
.TP
.B \-C
Colors! The locomotive exists outside of the bounds of monochrome.
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
Toyoda Masashi (mtoyoda@acm.org)
